version: '3.8'

services:
  server:
    build: ../pet-hotel-back-0.0.5
    container_name: pethotel_server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - 'DB_NAME=pethotel'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin_pwd'
      - 'DB_HOST=pethotel_db'
      - 'DB_PORT=5432'

  db:
    image: postgres:13.7-alpine
    container_name: pethotel_db
    ports:
      - "6541:5432"
    environment:
      - 'POSTGRES_DB=pethotel'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin_pwd'
