openapi: 3.0.1
info:
  title: 'PetHotel: Rooms Specification'
  description: Документация раздела по работе с номерами
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - description: API для работы с номерами
    name: room-controller
paths:
  /rooms:
    get:
      tags:
        - room-controller
      operationId: getAllRooms
      description: Получение списка номеров. Доступно только для пользователей с ролью BOSS или ADMIN. Вывод номеров происходит отдельно действующих, и отдельно скрытых, в зависимости от параметра isVisible.
      summary: Запрос списка номеров
      parameters:
        - name: X-PetHotel-User-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: isVisible
          in: query
          description: True - для действующих номеров, False - для скрытых номеров (для юзера называются удаленные)
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomDto'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - room-controller
      operationId: addRoom
      description: Добавление нового номера. Функция доступна только пользователям уровня BOSS и ADMIN.
      summary: Добавление нового номера
      parameters:
        - name: X-PetHotel-User-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomDto'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
  /rooms/{id}:
    get:
      tags:
        - room-controller
      operationId: getRoomById
      description: Получение карточки номера. Доступно только пользователям уровня BOSS и ADMIN.
      summary: Получение информации о номере
      parameters:
        - name: X-PetHotel-User-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: id
          in: path
          description: ID номера
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - room-controller
      operationId: deleteRoomById
      description: Безвозвратное удаление карточки номера. Доступно только пользователям уровня BOSS и ADMIN.
      summary: Удаление существующего номера (безвозвратно)
      parameters:
        - name: X-PetHotel-User-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: id
          in: path
          description: ID номера
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - room-controller
      operationId: updateRoom
      description: Изменение карточки номера. Доступно только пользователям уровня BOSS и ADMIN. Поле isVisible не изменяется.
      summary: Изменение информации о номере (кроме параметра видимости isVisible)
      parameters:
        - name: X-PetHotel-User-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: id
          in: path
          description: ID номера
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoomDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
  /rooms/{id}/unhide:
    patch:
      tags:
        - room-controller
      operationId: unhideRoomById
      description: В UI называется "Восстановление номера" (из удаленных). Изменение параметра видимости на TRUE, после чего номер отражается в сетке бронирований. Доступно только пользователям уровня BOSS и ADMIN. Кроме поля isVisible ничего не меняется.
      summary: Возвращает номер в статус "действующий"
      parameters:
        - name: X-PetHotel-User-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: id
          in: path
          description: ID номера
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
  /rooms/{id}/hide:
    patch:
      tags:
        - room-controller
      operationId: hideRoomById
      description: В UI называется "Удаление номера". Изменение параметра видимости на FALSE, после чего номер не отражается в сетке бронирований. Доступно только пользователям уровня BOSS и ADMIN. Кроме поля isVisible ничего не меняется. Из БД запись не удаляется.
      summary: Удаляет номер из списка действующих
      parameters:
        - name: X-PetHotel-User-Id
          in: header
          required: true
          schema:
            type: integer
            format: int64
        - name: id
          in: path
          description: ID номера
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoomDto'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        errors:
          description: Список ошибок из StackTrace
          type: array
          items:
            type: string
        message:
          description: Текст ошибки
          type: string
        reason:
          description: Кастомное описание причины
          type: string
        httpStatus:
          description: Код ответа
          type: string
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 EARLY_HINTS
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
        timeStamp:
          type: string
          format: date-time
    RoomDto:
      required:
        - number
        - type
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        number:
          description: Буквенно-цифровое обозначение номера
          example: 1D
          maxLength: 100
          minLength: 1
          type: string
        area:
          description: Площадь номера в квадратных метрах
          example: 6.0
          minimum: 0
          type: number
          format: double
        type:
          description: Тип номера
          type: string
          enum:
            - SMALL
            - BIG
            - EXOT
        description:
          description: Описание номера
          example: Номер для собак стандартный
          type: string
        isVisible:
          description: Текущий статус номера - действующий либо удаленный.
          example: true
          type: boolean
    UpdateRoomDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        number:
          description: Буквенно-цифровое обозначение номера
          example: 1D
          maxLength: 100
          minLength: 1
          type: string
        area:
          description: Площадь номера в квадратных метрах
          example: 6.0
          minimum: 0
          type: number
          format: double
        type:
          description: Тип номера
          type: string
          enum:
            - SMALL
            - BIG
            - EXOT
        description:
          description: Описание номера
          example: Номер для собак стандартный
          type: string

