DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS rooms;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(254)                            NOT NULL,
    role  VARCHAR(16)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

INSERT INTO users (name, email, role)
values ('boss', 'boss@mail.ru', 'ROLE_BOSS');

CREATE TABLE IF NOT EXISTS pets
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_pet         VARCHAR(250)                            NOT NULL,
    breed_pet        VARCHAR(250)                            NOT NULL,
    sex_pet          VARCHAR(13)                             NOT NULL,
    age_pet          INTEGER                                 NOT NULL,
    weight_pet       INTEGER                                 NOT NULL,
    diet_pet         VARCHAR(21)                             NOT NULL,
    medication_pet   BOOLEAN                                 NOT NULL,
    contact_pet      BOOLEAN                                 NOT NULL,
    photographed_pet BOOLEAN                                 NOT NULL,
    comments_pet     VARCHAR(1000),
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rooms
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number    VARCHAR(100)                            NOT NULL,
    price     REAL,
    size      REAL,
    type      VARCHAR(16)                             NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    CONSTRAINT pk_room PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS owners
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    email                   VARCHAR(254)                            NOT NULL,
    main_phone              VARCHAR(16)                             NOT NULL,
    optional_phone          VARCHAR(16),
    instagram               VARCHAR(255),
    youtube                 VARCHAR(255),
    facebook                VARCHAR(255),
    tiktok                  VARCHAR(255),
    twitter                 VARCHAR(255),
    telegram                VARCHAR(255),
    whatsapp                VARCHAR(255),
    viber                   VARCHAR(255),
    vk                      VARCHAR(255),
    prefer_communication    VARCHAR(16) DEFAULT 'MAIN_PHONE'          NOT NULL,
    car_registration_number varchar(9),
    CONSTRAINT pk_owner PRIMARY KEY (id),
    CONSTRAINT UQ_OWNER_EMAIL UNIQUE (email)
);



